# log frequency
val_check_interval: 1000
progress_bar_refresh_rate: 1

wandb:
  name: ${expname}
  project: CGFM_MP20
  entity: null
  log_model: True
  mode: 'online'
  group: ${expname}

wandb_watch:
  log: 'all'
  log_freq: 500

lr_monitor:
  logging_interval: "step"
  log_momentum: False
