expname: test

# metadata specialised for each experiment
core:
  version: 0.0.1
  tags:
    - ${now:%Y-%m-%d}

hydra:
  run:
    dir: ${oc.env:PROJECT_ROOT}/hydra/singlerun/${now:%Y-%m-%d}/${expname}/

  sweep:
    dir: ${oc.env:PROJECT_ROOT}/hydra/multirun/${now:%Y-%m-%d}/${expname}/
    subdir: ${hydra.job.id}

  job:
    env_set:
      WANDB_START_METHOD: thread
      WANDB_DIR: ${oc.env:PROJECT_ROOT}/wandb

defaults:
  - data: mp_20
  - logging: default
  - model: sgfm
  - optim: default
  - train: default
